### ISSUE TITLE
Add App Name to Splash screen

### ISSUE THREAD

**Issue by devarshukani** [OSS-Symbiosis/PixelPlay#2]
Add App Name "Pixel Play" below the App Icon in splash screen activtiy

Modify `activity_splash_screen.xml` file for adding name

Prevent using static name in TextView. Instead use `@string/app_name` to make it more dynamic for the future changes

**Comment by Naveed1891** [comment]
hi, i can do this...assign me this issue

**Comment by devarshukani** [comment]
@Naveed1891  Please go ahead and add the TextView.
Create a pull request and i'll review the code
